version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "happier-hour-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mjbew68n2jx8"
s3_prefix = "happier-hour-api"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
